services:
  cloudmoura-php:
    image: php:8.1-fpm
    container_name: cloudmoura-php
    restart: unless-stopped
    user: "1001:1001"
    volumes:
      - ./src:/var/www/html
      - ./.infra/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - npm-network

  cloudmoura-nginx:
    image: nginx:alpine
    container_name: cloudmoura-nginx
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./src:/var/www/html
      - ./.infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cloudmoura-php
    networks:
      - npm-network

networks:
  npm-network:
    external: true
