services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - cloudmoura-net

  cloudmoura:
    image: nginx:alpine
    container_name: cloudmoura
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - cloudmoura-net

networks:
  cloudmoura-net:
    name: cloudmoura-net