services:
  cloudmoura-php:
    image: php:8.1-fpm
    container_name: cloudmoura-php
    restart: unless-stopped
    user: "1001:1001"
    volumes:
      - ./src:/var/www/html
      - ./.infra/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./vendor:/var/www/html/vendor
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
    networks:
      - npm-network

  cloudmoura-nginx:
    image: nginx:alpine
    container_name: cloudmoura-nginx
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./src:/var/www/html
      - ./.infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cloudmoura-php
    networks:
      - npm-network

  composer:
    image: composer:2
    container_name: cloudmoura-composer
    volumes:
      - ./src:/var/www/html
      - ./vendor:/var/www/html/vendor
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
    working_dir: /var/www/html
    entrypoint: ["composer"]

networks:
  npm-network:
    external: true
